### ISSUE TITLE
[test] Why? :)

### ISSUE THREAD

**Issue by yauhenipakala** [demns/VisualStudioGitTest#1]
Recommend using [https://www.gitignore.io/](https://www.gitignore.io/)

**Comment by yauhenipakala** [comment]
If you use [Git Extensions](https://github.com/gitextensions/gitextensions), this functionality (support VS) is enabled by default.

**Comment by demns** [comment]
so ok, my steps are:

1) create project on git

2) copypaste link (as https://sdad.asdasda/s/blabl/abla.git)

3) goto team explorer (near the solution components)

4) home -> unsynced commits

5) enter link

6) publish

7) ...???? nothing happens. can't choose branch, can't create anything etc

**Comment by demns** [comment]
@ Recommend using https://www.gitignore.io/ @

yep, knew about it

also can choose such things from git init window, during the new project creation)

@ If you use Git Extensions @

I use 2013 VS which allows (am I right?) to do this without any kind of extentions
